stages:
  - ci
  - machines

Build CI targets:
  stage: ci
  tags:
    - nix

  script:
    - mkdir -p /etc/nix/
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix run .#ci

  timeout: 30 minutes

Build Machine targets:
  stage: machines
  tags:
    - nix # Run on the shared /nix/store builder

  script:
    - mkdir -p /etc/nix/
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix-env -i git-crypt
    - echo "$GITCRYPT_KEY" | base64 -d > /tmp/gitcrypt.key
    - echo "$(sha512sum /tmp/gitcrypt.key)"
    - git-crypt unlock /tmp/gitcrypt.key
    - nix run .#build_all

  timeout: 2h
